import Head from 'next/head';
import { useState } from 'react';
import {
  Input,
  FormControl,
  Container,
  Heading,
  Select,
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  useDisclosure,
  ModalBody,
  Flex,
  Box,
  Spacer,
} from '@chakra-ui/react';
import { trpc } from '@/utils/trpc';

export default function Home() {
  const [id, setId] = useState<number | null>(null);
  const [name, setName] = useState('');
  const [course, setCourse] = useState('');
  const [grade, setGrade] = useState('');
  const [date, setDate] = useState('');

  const [param, setParam] = useState<number | null>(null);

  const { isOpen: isM1, onOpen: openM1, onClose: closeM1 } = useDisclosure();
  const { isOpen: isM2, onOpen: openM2, onClose: closeM2 } = useDisclosure();

  const issue = trpc.issue.useMutation();
  const fetch = trpc.fetch.useMutation();

  const handleSubmit = async () => {
    const certificate = {
      id,
      name,
      course,
      grade,
      date,
    };
    issue.mutate(certificate);
    openM1();
    setId(null);
    setName('');
    setCourse('');
    setGrade('');
    setDate('');
  };

  const handleSearch = async () => {
    fetch.mutate({ id: param });
    openM2();
    setParam(null);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Container centerContent>
          <Heading as="h2" size="xl" my={4} noOfLines={1}>
            Certificate DApp
          </Heading>
          <Heading as="h4" size="md" my={2} noOfLines={1}>
            Issue Certificate
          </Heading>
          <FormControl my={2}>
            <Input
              type="number"
              min={0}
              placeholder="Enter Certificate ID"
              onChange={(e) => setId(Number(e.currentTarget.value))}
              value={id ? id : ''}
            />
          </FormControl>
          <FormControl my={2}>
            <Input
              type="text"
              placeholder="Enter Candidate Name"
              onChange={(e) => setName(e.currentTarget.value)}
              value={name}
            />
          </FormControl>
          <Select
            my={2}
            onChange={(e) => setCourse(e.currentTarget.value)}
            value={course}
          >
            <option hidden>Select Course</option>
            <option value="Certified Blockchain Associate">
              Certified Blockchain Associate
            </option>
            <option value="Certified Ethereum Developer">
              Certified Ethereum Developer
            </option>
            <option value="Certified Hyperledger Fabric Developer">
              Certified Hyperledger Fabric Developer
            </option>
            <option value="Certified Blockchain Architect">
              Certified Blockchain Architect
            </option>
          </Select>
          <Select
            my={2}
            onChange={(e) => setGrade(e.currentTarget.value)}
            value={grade}
          >
            <option hidden>Select Grade</option>
            <option value="S">S</option>
            <option value="A">A</option>
            <option value="B">B</option>
            <option value="C">C</option>
          </Select>
          <FormControl my={2}>
            <Input
              type="date"
              onChange={(e) => setDate(e.currentTarget.value)}
              value={date}
            />
          </FormControl>
          <Button
            my={2}
            colorScheme="teal"
            type="submit"
            onClick={handleSubmit}
          >
            Submit
          </Button>
        </Container>
      </section>
      <section>
        <Container centerContent my={8}>
          <Heading as="h4" size="md" my={2} noOfLines={1}>
            Fetch Certificate
          </Heading>
          <Flex w="full">
            <FormControl mx={2} my={2}>
              <Input
                type="number"
                min={0}
                placeholder="Enter Certificate ID"
                onChange={(e) => setParam(Number(e.currentTarget.value))}
                value={param ? param : ''}
              />
            </FormControl>
            <Button
              mx={2}
              my={2}
              colorScheme="teal"
              type="submit"
              onClick={handleSearch}
            >
              Search
            </Button>
          </Flex>
        </Container>
      </section>
      <Modal isOpen={isM1} onClose={closeM1}>
        <ModalOverlay />
        {issue.isError ? (
          <ModalContent>
            <ModalHeader>Error</ModalHeader>
            <ModalCloseButton />
            <ModalBody>{issue.error?.message}</ModalBody>
          </ModalContent>
        ) : (
          <ModalContent>
            <ModalHeader>Success</ModalHeader>
            <ModalCloseButton />
            <ModalBody>{issue.data?.message}</ModalBody>
          </ModalContent>
        )}
      </Modal>
      <Modal size={'lg'} isOpen={isM2} onClose={closeM2}>
        <ModalOverlay />
        {fetch.isError ? (
          <ModalContent>
            <ModalHeader>Error</ModalHeader>
            <ModalCloseButton />
            <ModalBody>{fetch.error?.message}</ModalBody>
          </ModalContent>
        ) : (
          <ModalContent>
            <ModalHeader mx={'auto'}>Certificate</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Container centerContent>
                <Heading as="h4" size="md" mb={8} noOfLines={1}>
                  AKA-DEMY
                </Heading>
                <p>This is to certify that</p>
                <Heading as="h4" size="md" my={4} noOfLines={1}>
                  {fetch.data?.name}
                </Heading>
                <p>has successfully completed</p>
                <Heading as="h5" size="md" my={2} noOfLines={1}>
                  {fetch.data?.course}
                </Heading>
                <p>with</p>
                <Heading as="h5" size="md" my={2} noOfLines={1}>
                  {fetch.data?.grade}
                </Heading>
              </Container>
              <Flex mt={8} mb={4} mx={2}>
                {/* <Box> */}
                <p>Date: {fetch.data?.date}</p>
                <Spacer />
                <p>Certificate ID: {fetch.data?.id}</p>
                {/* </Box> */}
              </Flex>
            </ModalBody>
          </ModalContent>
        )}
      </Modal>
    </>
  );
}
